### ISSUE TITLE
some snippets not expanding

### ISSUE THREAD

**Issue by ohnoitsaustin** [scottanthonymurray/rivet-emmet#1]
In VS Code, the snippets in the `abbreviations` section of the .json file do not expand to the corresponding HTML, but to a custom tag with the name of the snippet. For instance, typing `rvt-button` expands to `<rvt-button></rvt-button>`, rather than `<button class="rvt-button"></button>`. Are the snippets in that section meant to work differently?

The short codes in the `snippets` section of the file (such as `rvt-alert`) are expanding to their corresponding markup correctly.

**Comment by scottanthonymurray** [comment]
Thanks for the heads up! Looking at the VS Code docs, it looks like their implementation of Emmet is different from the one described on the main Emmet site. I'll take a look and see if I can get this working for VS Code.

**Comment by scottanthonymurray** [comment]
Found the culprit here: https://code.visualstudio.com/docs/editor/emmet#_using-custom-emmet-snippets

Wish that info was on the main Emmet site

**Comment by scottanthonymurray** [comment]
Fixed in newest commit
