### ISSUE TITLE
Update the starter template snippet to include IE compatibility mode meta tag

### ISSUE THREAD

**Issue by levimcg** [scottanthonymurray/rivet-emmet#3]
We discovered a bug in the starter template a while back where if you are using IE11 in compatibility mode it totally breaks the rivet JavaScript if the IE compatibility meta tag:

`<meta http-equiv="X-UA-Compatible" content="IE=edge">`

The `rvt-start` snippet is great! We just need to add the tag to the `<head>` block.

**Comment by scottanthonymurray** [comment]
Fixed in commit [bf4f521](https://github.com/indiana-university/rivet-emmet/commit/bf4f52100eb434c92949e8f67bd4f156bec6abf5).
